version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:latest
    steps:
      - checkout
      - run: sudo apt-get update
      - run: npm ci
      - run:
          command: |
            npx playwright install chromium
            npx playwright install-deps chromiumn
